### ISSUE TITLE
Consider adding binary fuse filters

### ISSUE THREAD

**Issue by lemire** [bnclabs/xorfilter#16]
We have updated the C, C++, Go and Java code with a new breed of filters (binary fuse filters). The implementation is nearly identical, but the construction time is at least 2x faster, and the resulting filter is significantly smaller.

Binary fuse 8 and fuse 16 in C:

https://github.com/FastFilter/xor_singleheader/blob/master/include/binaryfusefilter.h

Binary fuse 8 in Go:

https://github.com/FastFilter/xorfilter/blob/master/binaryfusefilter.go

**Comment by ayazhafiz** [comment]
@lemire can you elaborate on why the construction time for binary fuse is significantly faster? I understand that the structure of the fuse filters is such that the total space consumed is smaller, but if I recall correctly fuse filter construction may fail if there aren't enough keys.

Edit: I see in https://github.com/FastFilter/xor_singleheader/issues/21 you have addressed the "fails on too few keys" limitation of the previous fuse hypergraph-based filter. I am curious if you have any more resources explaining your change to the construction algorithm.

**Comment by lemire** [comment]
@ayazhafiz 

We worked on something new, which we call the binary fuse filter. It has the same lookup performance as the xor filter, but it has 2x the construction speed (roughly) and uses significantly less memory. If you have many keys (say a million), then it is much better.

We have an upcoming preprint, I can share it with you, just email me at lemire@gmail.com and I will send you the PDF.

**Comment by prataprc** [comment]
Ported the Fuse8 and Fuse16 to rust.

ref1: https://github.com/bnclabs/xorfilter/blob/master/src/fuse8.rs
ref2: https://github.com/bnclabs/xorfilter/blob/master/src/fuse16.rs

Following are the results for a set of 10-million `u64` keys:

|             |  build 10M keys |  membership |   FPP   |  Bits/Entry |
|-------------|-----------------|-------------|---------|-------------|
| Xor8-C      |   1.206 secs    |    NA       | 0.389 % |  9.84 bits  |
| Xor8-rust   |   1.809 secs    | 61.716 ns   | 0.392 % |  9.84 bits  |
| Fuse8-C     |   0.508 secs    |    NA       | 0.390 % |  9.02 bits  |
| Fuse8-rust  |   0.611 secs    | 42.657 ns   | 0.392 % |  9.02 bits  |
| Fuse16-C    |   0.515 secs    |    NA       | 0.001 % | 18.04 bits  |
| Fuse16-rust |   0.621 secs    | 54.657 ns   | 0.001 % | 18.03 bits  |

* **Build time** is measured in `Seconds`, for 10 million entries.
* **Membership** is measured in `Nanosec`, for single lookup in a set of 10 million entries.
* **FPP** = False Positive Probability measured in percentage

I hope these number make sense.

Thanks for the awesome work.

**Comment by lemire** [comment]
@prataprc that's great work. You seem to be getting a 3x speed up (Xor8-rust vs Fuse8-rust) which is fantastic... especially since the final result is even more compact.

**Comment by prataprc** [comment]
Released 0.5.0 with Fuse8 and Fuse16 implementation, now available at https://crates.io/crates/xorfilter-rs

**Comment by lemire** [comment]
Fantastic news!
