### ISSUE TITLE
Tests take a long time to complete

### ISSUE THREAD

**Issue by drmingdrmer** [bnclabs/xorfilter#21]
- `cargo test --debug` takes `27m 27s`: https://github.com/prataprc/xorfilter/actions/runs/3351476266/jobs/5552950294

- `cargo test --release` takes `3m 54s`: https://github.com/prataprc/xorfilter/actions/runs/3351476266/jobs/5552950199

Is it all right to remove the **debug** mode test(line-22) and only run tests in **release** mode in github CI?
https://github.com/prataprc/xorfilter/blob/a1d19318cf466615a574679856c01d67fd997169/.github/workflows/simple-build-test.yml#L20-L22

https://github.com/prataprc/xorfilter/blob/a1d19318cf466615a574679856c01d67fd997169/.github/workflows/simple-build-test.yml#L41-L45

**Comment by prataprc** [comment]
Yes. Make sense. I was only running these tests locally.
