### ISSUE TITLE
Allow arbitrary value types

### ISSUE THREAD

**Issue by mre** [bnclabs/xorfilter#3]
Are you planning to add support for arbitrary value types like strings?
Would be helpful to have a similar interface to [HashSet](https://doc.rust-lang.org/std/collections/struct.HashSet.html) or [cuckoofilter](https://github.com/mre/rust-cuckoofilter)  eventually.  

Use-case: I'm interested in testing XOR-filters as a search datastructure for [tinysearch](https://github.com/mre/tinysearch).

**Comment by prataprc** [comment]
Arbitrary value types ? Are you proposing something like:

```rust
populate<T: Hash>(keys: &Vec<T>) -> Box<Xor8>
```

> Would be helpful to have a similar interface to HashSet or cuckoofilter eventually.

Xor8 Filter is immutable data structure, hence it is not possible to implement add() or delete() methods.

**Comment by mre** [comment]
> Xor8 Filter is immutable data structure, hence it is not possible to implement add() or delete() methods.

That's true. Was thinking of a builder pattern to provide the same API:

```rust
let mut builder = Xor8Builder::new();
builder.insert("A Dance With Dragons".to_string());
let books = builder.build() // This creates the immutable datastructure
```

`insert` would be generic over `T`:

```rust
pub fn insert(&mut self, value: T) -> bool {
  todo!()
}
```

Using Xor filters instead of `HashSet` would then require minimal code changes,
but I could understand if that design doesn't align with your goals for the crate.

**Comment by prataprc** [comment]
I am open to pull request. We can create a separate ``Builder`` type and implement  a method `into_xor8()` to obtain the immutable Xor8 value.

**Comment by uijin** [comment]
IMHO, any type which implement [Hash trait](https://doc.rust-lang.org/std/hash/trait.Hash.html) could get `u64` hash value, used as key for Xor filters.

Would like to know the feasibility of this solution.

**Comment by prataprc** [comment]
Yes it is feasible ! Please check with @mre if you did like to take up this implementation.

**Comment by mre** [comment]
Hey @uijin,
if you want to give it a shot, go ahead. I like your idea lot.

**Comment by prataprc** [comment]
Almost all of the feature requested is implemented. Documentation is added to publicly exposed API. Feel free to open separate issues for fixes and corrections.

Closing it.
